### ISSUE TITLE
Energy data from recorder stopt working

### ISSUE THREAD

**Issue by bafplus** [cyberjunky/home-assistant-toon_smartmeter#33]
No energy data is comming from about 12:00 yesterday.
Might be due to upgrade of Core to 2021.9.
See this issue for more details: https://github.com/home-assistant/core/issues/55918

Seems Toon related but might be a Core issue.

**Comment by KRGT-NL** [comment]
Core version: core-2021.9.4
Integration version: from 6 days ago.

Some logging:

`Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:258
Integration: Sensor (documentation, issues)
First occurred: 6:56:33 (3 occurrences)
Last logged: 6:56:49

Entity sensor.toon_p1_power_use_high from integration toon_smartmeter has state class total_increasing, but its state is not strictly increasing. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+recorder%22
Entity sensor.toon_p1_power_prod_high from integration toon_smartmeter has state class total_increasing, but its state is not strictly increasing. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+recorder%22
Entity sensor.toon_p1_power_use_low from integration toon_smartmeter has state class total_increasing, but its state is not strictly increasing. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+recorder%22`

**Comment by Bart-1992** [comment]
I got the exact same error, my energy stats also stopped working since yesterday about 12 o'clock ( after upgrading to 2021.9 ).

**Comment by cyberjunky** [comment]
Please try to use the 'x Cnt x' sensors instead those are only increasing.

**Comment by Bart-1992** [comment]
I've had 'x Cnt x' for gas, but that one is also not working unfortunately

**Comment by cyberjunky** [comment]
@Bart-1992 with the same error or a difference one?

**Comment by Bart-1992** [comment]
Unfortunately i don't get a specific error message for gas, but the following (related?)recorder errors do occur :

````
2021-09-08 16:26:20 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb._exceptions.ProgrammingError) nan can not be used with MySQL
[SQL: INSERT INTO statistics (created, metadata_id, start, mean, min, max, last_reset, state, sum) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (datetime.datetime(2021, 9, 8, 14, 26, 20, 555490, tzinfo=datetime.timezone.utc), 409, datetime.datetime(2021, 9, 6, 9, 0, tzinfo=datetime.timezone.utc), None, None, None, None, nan, nan)]
(Background on this error at: https://sqlalche.me/e/14/f405)
2021-09-08 16:26:21 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb._exceptions.ProgrammingError) nan can not be used with MySQL
[SQL: INSERT INTO statistics (created, metadata_id, start, mean, min, max, last_reset, state, sum) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (datetime.datetime(2021, 9, 8, 14, 26, 20, 555490, tzinfo=datetime.timezone.utc), 409, datetime.datetime(2021, 9, 6, 9, 0, tzinfo=datetime.timezone.utc), None, None, None, None, nan, nan)]
(Background on this error at: https://sqlalche.me/e/14/f405) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2021-09-08 16:26:21 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb._exceptions.ProgrammingError) nan can not be used with MySQL
[SQL: INSERT INTO statistics (created, metadata_id, start, mean, min, max, last_reset, state, sum) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (datetime.datetime(2021, 9, 8, 14, 26, 20, 555490, tzinfo=datetime.timezone.utc), 409, datetime.datetime(2021, 9, 6, 9, 0, tzinfo=datetime.timezone.utc), None, None, None, None, nan, nan)]
(Background on this error at: https://sqlalche.me/e/14/f405) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2021-09-08 16:26:21 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb._exceptions.ProgrammingError) nan can not be used with MySQL
[SQL: INSERT INTO statistics (created, metadata_id, start, mean, min, max, last_reset, state, sum) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (datetime.datetime(2021, 9, 8, 14, 26, 20, 555490, tzinfo=datetime.timezone.utc), 409, datetime.datetime(2021, 9, 6, 9, 0, tzinfo=datetime.timezone.utc), None, None, None, None, nan, nan)]
(Background on this error at: https://sqlalche.me/e/14/f405) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2021-09-08 16:26:21 ERROR (Recorder) [homeassistant.components.recorder] SQLAlchemyError error processing event StatisticsTask(start=datetime.datetime(2021, 9, 6, 9, 0, tzinfo=datetime.timezone.utc)): This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb._exceptions.ProgrammingError) nan can not be used with MySQL
[SQL: INSERT INTO statistics (created, metadata_id, start, mean, min, max, last_reset, state, sum) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (datetime.datetime(2021, 9, 8, 14, 26, 20, 555490, tzinfo=datetime.timezone.utc), 409, datetime.datetime(2021, 9, 6, 9, 0, tzinfo=datetime.timezone.utc), None, None, None, None, nan, nan)]
(Background on this error at: https://sqlalche.me/e/14/f405) (Background on this error at: https://sqlalche.me/e/14/7s2a)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 657, in _process_one_event_or_recover
self._process_one_event(event)
File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 763, in _process_one_event
self._run_statistics(event.start)
File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 746, in _run_statistics
if statistics.compile_statistics(self, start):
File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 306, in wrapper
return job(instance, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 215, in compile_statistics
metadata_id = _update_or_add_metadata(
File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 151, in _update_or_add_metadata
old_metadata_dict = _get_metadata(hass, session, [statistic_id], None)
File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 257, in _get_metadata
result = execute(baked_query(session).params(statistic_ids=statistic_ids))
File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 115, in execute
result = list(qry)
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/baked.py", line 382, in __iter__
return self._iter().__iter__()
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/baked.py", line 412, in _iter
result = self.session.execute(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
conn = self._connection_for_bind(bind)
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
return self._transaction._connection_for_bind(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
self._assert_active()
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 601, in _assert_active
raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb._exceptions.ProgrammingError) nan can not be used with MySQL
[SQL: INSERT INTO statistics (created, metadata_id, start, mean, min, max, last_reset, state, sum) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (datetime.datetime(2021, 9, 8, 14, 26, 20, 555490, tzinfo=datetime.timezone.utc), 409, datetime.datetime(2021, 9, 6, 9, 0, tzinfo=datetime.timezone.utc), None, None, None, None, nan, nan)]
(Background on this error at: https://sqlalche.me/e/14/f405) (Background on this error at: https://sqlalche.me/e/14/7s2a)
````

**Comment by cyberjunky** [comment]
Has todo with this: 
```
(MySQLdb._exceptions.ProgrammingError) nan can not be used with MySQL
```
But I filter as much as NaN/nan values already, and nothing major changed in my code, but perhaps it's in issue in HA core code.

**Comment by cyberjunky** [comment]
https://github.com/home-assistant/core/pull/55943

**Comment by bafplus** [comment]
> [home-assistant/core#55943](https://github.com/home-assistant/core/pull/55943)

Ah, that should fix it...now we wait for 2021.9.5 :-)

**Comment by Bart-1992** [comment]
Indeed has nothing to do with Toon. Reverted back to 2021.9.1, and everything started working again ( data since install of 2021.9.5 are not lost ;)).
